[System.Serializable]
public enum StatusEffectId
{
    None = 0,
    Poison = 1,
    BadlyPoisoned = 2,
    Paralyzed = 3,
    Sleep = 4,
    Frozen = 5,
    Burn = 6,
    LeechSeed = 7,
    Charmed = 8,
    Confused = 9,
    MoveCharge = 10,
    FireVortex = 11,
    Sunny = 12,
    Rainy = 13,
    Hailing = 14,
    Charged = 15,
    Hopeless = 16,
    Flinch = 17,
    Frostbite = 18,
    RepeatMove = 19,
    Protected = 20,
}
