[System.Serializable]
public enum PokemonBaseId
{
    Bulbasaur = 1,
    Ivysaur = 2,
    Venusaur = 3,
    Charmander = 4,
    Charmeleon = 5,
    Charizard = 6,
    Squirtle = 7,
    Wartortle = 8,
    Blastoise = 9,
    Oddish = 43,
    Gloom = 44,
    Vileplume = 45,
    Gastly = 92,
    Haunter = 93,
    Gengar = 94,
    Scyther = 123,
    Ralts = 280,
    Kirlia = 281,
    Gardevoir = 282,
    Starly = 396,
    Buneary = 427,
    Lopunny = 428,
    Mimikyu = 778,
}
