public enum SaveElementId
{
    playerName = 0,
    starterPickedId = 1,
    characterModelId = 2,
    akaneFirstEncounterWon = 3,
    storyProgress = 4,
    timeOfDay = 5,
    tediursaHelpCompleted = 6,
    erikFirstEncounterResult = 7,
    akaneSecondEncounterWon = 8,
    staraptorBerriesProgress = 9,
    roseradeAmbush = 10,
    roseradePicnic = 11,
    pokedexEnabled = 12,
    gymGrassLoses = 13,
    akaneForestMoment = 14,
    money = 15,
    tacticsTutorial = 16,
    shopProgress = 17,
    expShare = 18,
    akaneRelationship = 100,
    danteRelationship = 101,
    erikRelationship = 102,
    tansyRelationship = 103,
    bobRelationship = 104,
    startedTypePicked = 1001, // 1 is grass, 2 water, 3 fire
    tansyProtectEachother = 1002,
    tansyWasBraver = 1003,
    danteFirstBattleGiveUp = 1004,
    TeamPlasmaAnswer = 1005, // 0 = Team Plasma Bad, 1 = Team Plasma Good, 2 = Team Plasma Misguided
}
